### ISSUE TITLE
Run-time failure related to use of type parameters and partial application

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-runtime#48]
## Describe the bug
Run-time failure related to use of type parameters and partial application

## To Reproduce
Create project with `Bug.qs` with content below and run `PrintAllPaulis()` operation.
```
namespace Buggy {
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    operation PrintPaulies( paulis : Pauli[] ) : Unit { Message($"{paulis}"); }

    operation ApplyComposed<'U,'V>( op : ('U => Unit), fn : ('V -> 'U), arg : 'V) : Unit {
        op(fn(arg));
    }

    function ArrayFromIndicies<'T>( values : 'T[], indicies : Int[] ) : 'T[] {
        mutable arr = new 'T[Length(indicies)];
        for( i in 0 .. Length(indicies) - 1) {
            set arr w/= i <- values[indicies[i]];
        }
        return arr;
    }

    operation IterateThroughCartesianPowerT<'T> (power : Int, values : 'T[], op : ('T[] => Unit)) : Unit {
        let opInt = ApplyComposed(op, ArrayFromIndicies(values,_),_);
        IterateThroughCartesianPower(power, Length(values), opInt);
    }

    operation PrintAllPaulis() : Unit {
        IterateThroughCartesianPowerT(3, [PauliI,PauliX,PauliY,PauliZ], PrintPaulies);
    }
}
```

## Expected behavior
64 lines of all possible combinations of 3 Pauli operators printed to console.

## Actual behavior
Run-time failure with the following data:
```
  Message: 
    System.MissingMethodException : Constructor on type 'Microsoft.Quantum.Simulation.Core.IQArray`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
  Stack Trace: 
    at RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    at PartialMapper.CastTuple(Type targetType, Object value)
    at PartialMapper.CastTuple(Type targetType, Object value)
    at <>c__DisplayClass9_0`2.<Create>b__0(P argTuple)
    at FunctionPartial`3.<get_Body>b__16_0(P a)
    at Function`2.Apply[GenO](Object args)
    at GenericCallable.Apply[O](Object args)
    at <>c.<get_Body>b__7_0(ValueTuple`3 __in__) in Bug.qs line: 8
    at OperationPartial`3.<get_Body>b__20_0(P a)
    at Operation`2.Apply(I a)
    at Operation`2.Apply[GenO](Object args)
    at GenericCallable.Apply[O](Object args)
    at <>c.<get_Body>b__11_0(ValueTuple`2 __in__)
    at Operation`2.Apply(I a)
    at ICallable<I,O>.Apply(I args)
    at IterateThroughCartesianPower.<get_Body>b__15_0(ValueTuple`3 __in__)
    at Operation`2.Apply(I a)
    at ICallable<I,O>.Apply(I args)
    at IterateThroughCartesianPowerT`1.<get_Body>b__23_0(ValueTuple`3 __in__) in Bug.qs line: 21
```

## System information
- OS: Windows 
- .NET Core Version: 2.2.401

**Comment by anpaz-msft** [comment]
From the strack-trace, looks like:

`ArrayFromIndicies` is not figuring out that `'T` is of type `Pauli` (which is strange, since `'T` is in the `values` argument) so it defaults to object `-->` that causes that the resolved type for the array is `object[]`, but looks like `QArray` doesn't support objects so it fails.

This seems related to #47, however, for this one I would start on [GenericaCallable.FindCallable](https://github.com/microsoft/qsharp-runtime/blob/2f1d833591dac0e33326d82d1d6a4d92c85b3586/src/Simulation/Core/Generics/GenericCallable.cs#L71) to figure out why the Type parameter `'T` from `ArrayFromIndicies` is not correctly identified.

**Comment by bettinaheim** [comment]
I did a quick investigation and the problem is that IsValidValue(Type targetType, object partialValues) will fail for the target type being an IQArray of objects and the partialValues being a concrete array of something (Paulis in this case). This is unfortunately how ArrayFromIndicies(values,_) currently get's translated.

**Comment by bettinaheim** [comment]
The issue is that we would need to delay the construction of the mapper, or have a way to represent a generic mapper. Since that work will become obsolete when C# needs to be generated only for monomorphized code, I suggest to defer addressing this issue until then.
