### ISSUE TITLE
QCTraceSimulator errors with "Sequence contains no elements."

### ISSUE THREAD

**Issue by wyoumansUSF** [microsoft/qsharp-runtime#542]
## Describe the bug
When creating a new QCTraceSimulator I get `Unhandled exception. System.InvalidOperationException: Sequence contains no elements`.

## To Reproduce
I started a new project with the commands:

```
dotnet new classlib -lang Q# -o quantum
dotnet new console -lang C# -o host
cd host
dotnet add reference ../quantum/quantum.csproj
```

Then change `host/Program.cs` to the following and run.
```
using System;
using Microsoft.Quantum.Simulation.Core;
using Microsoft.Quantum.Simulation.Simulators;
using Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators;

namespace host
{
    class Program
    {
        static void Main(string[] args)
        {
            var sim = new QCTraceSimulator();
        }
    }
}

```

## Expected behavior
I expect this code to not error and terminate quietly.

## Actual behavior
The code errors with:

```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.Implementation.QCTraceSimulatorImpl.RegisterPrimitiveOperationsGivenAsCircuits(Assembly coreAssembly)
   at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.Implementation.QCTraceSimulatorImpl..ctor(QCTraceSimulatorConfiguration config, Assembly coreAssembly)
   at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.QCTraceSimulator..ctor(QCTraceSimulatorConfiguration config, Assembly coreAssembly)
   at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.QCTraceSimulator..ctor()
   at host.Program.Main(String[] args) in /path/to/host/Program.cs:line 12
```

## System information
- OS: Ubuntu 18.04

- .NET Core Version: 5.0.103

- IQ# Version 
 ```
iqsharp: 0.15.2102129448
Jupyter Core: 1.5.0.0
.NET Runtime: .NETCoreApp,Version=v3.1
```

- Python Version (if applicable) NA

**Comment by tcNickolas** [comment]
I'm getting this issue too, with slightly more complicated code that used to work with QDK 0.12.20100504 (and as recently as 0.15.2101125897) but throws this error with 0.15.2102129448. 

You can repro the repro [here](https://github.com/tcNickolas/qce20-curriculum-development/tree/main/resource-estimation) (the project version of the code). It does contain H gates, so it shouldn't be the same as #540.
