### ISSUE TITLE
Memory leak in QuantumSimulator

### ISSUE THREAD

**Issue by jgukelberger** [microsoft/qsharp-runtime#91]
## Describe the bug
Apparently `QuantumSimulator` does not release upon its destruction the memory reserved for wavefunction storage. This is not noticeable in programs that exit immediately after destroying their single simulator object. However, when the simulator is repeatedly created and deleted, the leak is very noticeable. (As mentioned in #35 creating a new simulator is currently the only way to reset the global phase.)

## To Reproduce
Here's a minimal working example:

Driver.cs:
```
using System;

using Microsoft.Quantum.Simulation.Core;
using Microsoft.Quantum.Simulation.Simulators;

namespace Bell
{
    class Driver
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 100; ++i)
            {
                using (var qsim = new QuantumSimulator())
                {
                    HelloQ.Run(qsim).Wait();
                }
                
                System.Console.WriteLine($"{i}: Press any key to continue...");
                System.Console.ReadKey();
            }
        }
    }
}
```

Operations.qs:
```
namespace Bell
{
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    operation HelloQ () : Unit {
        using (register = Qubit[26]) {
        }
    }
}
```

## Actual behavior
Start the program and a process viewer (e.g. Task Manager on Windows), observe memory usage of the process increasing by ~1 GB on every key press. At some point, when the process has grown to >50 GB on my system, the following exception is raised:
```
 Unhandled exception. System.AggregateException: One or more errors occurred. (External component has thrown an exception.)
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.QSimQubitManager.AllocateOne(UInt32 id, UInt32 qubit_id)    at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.QSimQubitManager.AllocateOneQubit(Boolean usedOnlyForBorrowing)
   at Microsoft.Quantum.Simulation.Common.QubitManager.Allocate(Int64 numToAllocate)
   at Bell.HelloQ.<get_Body>b__14_0(QVoid __in__) in C:\Users\jagukelb\repos\qapps\tmp\Bell\Operations.qs:line 7           at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
   at Microsoft.Quantum.Simulation.Core.Operation`2.Apply[GenO](Object args)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Bell.Driver.Main(String[] args) in C:\Users\jagukelb\repos\qapps\tmp\Bell\Driver.cs:line 16
```
I assume that is the C++ backend failing to allocate memory.

## Expected behavior
All memory related to the quantum simulation should be released at the exit from the `QuantumSimulator` object's `using` block.

## System information
- Windows 10
- .NET Core Version: 3.0.100
- QDK versions: at least 0.9 and 0.10 exhibit the bug, earlier not tested

**Comment by jgukelberger** [comment]
This has been fixed in the PR linked above, including latest QDK release.
