### ISSUE TITLE
Consider sanitizing the native part of the QuantumSimulator

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#972]
Looks like we never ended up sanitizing the native part of the QuantumSimulator.
Of and on that part crashes during the CI tests. Details and examples are in "Build Setup and Repos" Teams channel, conversation with topic "Crashes on native simulator" started on 2022.03.23 9:30am PT by Andres.
<details><summary>Crash extract</summary>

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.SetSeedNative(UInt32, UInt32)
--------------------------------
   at Microsoft.Quantum.Simulation.Simulators.Tests.QuantumSimulatorTests.QSimVerifyX()
   at Microsoft.Quantum.Simulation.Simulators.Tests.QuantumSimulatorTests.<QSimMultithreading>b__4_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
</details>

We need to sanitize the native part.
* Add warnings and sanitizers in the Debug config ([example](https://github.com/microsoft/qsharp-runtime/blob/499c068d3addc187b8cba30f718ba68f7d4b0e84/src/Qir/Common/cmake/qir_cmake_include.cmake#L56-L216)).
* Add the sanitized pipeline (example [yml](https://github.com/microsoft/qsharp-runtime/blob/main/build/ci-codecheck.yml), [pipeline](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=34&nonce=cvsTaGdiI886udsKu34cfw%3D%3D&branch=main)) that 
  * Builds the Debug version 
  * Runs the QuantumSimulator tests against Debug version

After fixing all the found bugs we probably need to disable that pipeline until some other issues need to be sanitized.

**Comment by kuzminrobin** [comment]
[Related Commit](https://github.com/microsoft/qsharp-runtime/commit/10211ce9e59e58689c92df1774920a8edc02aae3).
